// ─── School Calendar Chart — Week Strips ──────────────────────
// 23 districts × up to 47 calendar-aligned weeks. Each cell is a
// single week classified by its dominant disruption:
//
//   u — unbroken        ink filled
//   e — early_release   amber filled
//   t — teacher_only    sepia filled
//   h — holiday         orange filled
//   b — break           hollow (parchment with sepia outline)
//
// Strips are calendar-aligned (not left-aligned), so Thanksgiving,
// winter break, and spring break appear in the same column across
// every district — the rhythm of the year becomes visible.
//
// Data source: data/school-calendars/per-week.json, generated by
// data/school-calendars/scripts/build_weeks.py from the per-day
// extraction JSONs. Every 'u' count reconciles exactly to the
// aggregate `unbroken_five_day_weeks` in districts.csv. The chart
// is NOT a schematic approximation of the dataset — it IS the
// dataset.
//
// Typography via @chenglou/pretext for Unicode-aware measurement
// and line breaking. Palette copied from the Meridian parchment
// renderer so this essay sits consistently with the rest of the
// site's knowledge-cartography aesthetic.

import { prepareWithSegments, layoutWithLines } from "@chenglou/pretext"

// ─── Data (baked from per-week.json, 2026-04-05) ──────────────

type District = {
  name: string
  state: string
  pct: number
  streak: number
  weeks: string
  week_count: number
  offset: number
}

const ANCHOR_MONDAY = "2025-08-04" // Monday of column 0
const TOTAL_COLUMNS = 47

// Month labels for the column-header strip. Each label sits at the
// Monday-of-the-month-that-begins-in-that-column. Computed once from
// the anchor so we don't ship a date library.
const MONTH_STARTS: { col: number; label: string }[] = [
  { col: 0, label: "Aug" },
  { col: 4, label: "Sep" },
  { col: 9, label: "Oct" },
  { col: 13, label: "Nov" },
  { col: 17, label: "Dec" },
  { col: 22, label: "Jan" },
  { col: 26, label: "Feb" },
  { col: 30, label: "Mar" },
  { col: 35, label: "Apr" },
  { col: 39, label: "May" },
  { col: 43, label: "Jun" },
]

const DISTRICTS: District[] = [
  { name: "Cobb County", state: "GA", pct: 73.2, streak: 6, weeks: "uuuuhuubuuuuutuubuuebbtuhuuubuuuuuubuuuuu", week_count: 41, offset: 0 },
  { name: "Gwinnett County", state: "GA", pct: 70.7, streak: 5, weeks: "uuuuhuuuubbeuuuubuuubbuuhuubbueuuuubuuuuu", week_count: 41, offset: 0 },
  { name: "Hawaii (statewide)", state: "HI", pct: 69.0, streak: 7, weeks: "uhuuhuuuubuuuuhuhuuubbtuhuuuhuuubhhuuuuuuu", week_count: 42, offset: 0 },
  { name: "Memphis-Shelby County", state: "TN", pct: 68.3, streak: 5, weeks: "uuuuhuuuuubuuuhubuuubbbuhuuthuuububbuuuuu", week_count: 41, offset: 0 },
  { name: "Houston ISD", state: "TX", pct: 68.3, streak: 7, weeks: "uuhuuuhuuuutuubuuubbtuhuuthuubuuhuuuuuuuh", week_count: 41, offset: 1 },
  { name: "Palm Beach County", state: "FL", pct: 64.3, streak: 7, weeks: "uuuhuuhhutuuutubuuubbtuhuuutuuubthuuuuuuuh", week_count: 42, offset: 1 },
  { name: "Duval County", state: "FL", pct: 63.4, streak: 6, weeks: "uuuhuuuuhtuuuhubuubbbtuhuuubuubbuhhuuuuuu", week_count: 41, offset: 1 },
  { name: "Chicago Public Schools", state: "IL", pct: 63.4, streak: 7, weeks: "uuhuutuuhutuhuhuuubbtuhuuuhuuutbtuuuuuuuh", week_count: 41, offset: 2 },
  { name: "Cypress-Fairbanks ISD", state: "TX", pct: 62.5, streak: 6, weeks: "uuhuuuuthuuhuubuubbbtuhuuttuubuuhtuuuuuu", week_count: 40, offset: 2 },
  { name: "Dallas ISD", state: "TX", pct: 62.5, streak: 4, weeks: "uuhuuuuhtuutuubuuebbtuhuuuhuuubuhtuuutuu", week_count: 40, offset: 2 },
  { name: "Clark County", state: "NV", pct: 61.0, streak: 6, weeks: "uuuhutuuutthuhubuuubbuuhtuthuuubuttuuuuuu", week_count: 41, offset: 1 },
  { name: "Charlotte-Mecklenburg", state: "NC", pct: 61.0, streak: 6, weeks: "uhtuttuuuuthubuuubbuuhuuututututbuuuuuuhu", week_count: 41, offset: 3 },
  { name: "Baltimore County", state: "MD", pct: 56.1, streak: 6, weeks: "uhuuttuhteuetbuuubbuehuuuhuuutubbuuuuuuhu", week_count: 41, offset: 3 },
  { name: "Montgomery County", state: "MD", pct: 56.1, streak: 5, weeks: "huuttuttutuuhuuubbuuhtuuheuutubbtuuuuuhuu", week_count: 41, offset: 4 },
  { name: "Wake County", state: "NC", pct: 56.1, streak: 3, weeks: "uhuutuuttuthubuuubbuuhtuutututubtuutuuuhu", week_count: 41, offset: 3 },
  { name: "Fairfax County", state: "VA", pct: 54.8, streak: 4, weeks: "uheuuhueeethubuuubbuuhtuuhuuuuebtutuuuuhuu", week_count: 42, offset: 3 },
  { name: "New York City DOE", state: "NY", pct: 52.4, streak: 6, weeks: "uuhhuhhuthebuuubbuuhuuubueehubbuuuuuuhtuhu", week_count: 42, offset: 4 },
  { name: "Polk County", state: "FL", pct: 51.2, streak: 4, weeks: "uuehuueuutueuhebuuebbtehuuehuuebuhuueuuuu", week_count: 41, offset: 1 },
  { name: "Prince George's County", state: "MD", pct: 51.2, streak: 4, weeks: "heuhhutueutubuuebbuuheuehuuuuebbueuuuuhuu", week_count: 41, offset: 4 },
  { name: "Broward County", state: "FL", pct: 50.0, streak: 5, weeks: "uuuhuuhhettuuhubuuebbtuhuuehuutbuhtuuuuueh", week_count: 42, offset: 1 },
  { name: "Orange County", state: "FL", pct: 50.0, streak: 5, weeks: "uuhhutuettuethubuuubbtuheutueuttuubuuuuu", week_count: 40, offset: 1 },
  { name: "Philadelphia", state: "PA", pct: 38.1, streak: 2, weeks: "uheuhhthuuhhubueubbueheuehuuehubeeuueuhhue", week_count: 42, offset: 3 },
  { name: "Miami-Dade County", state: "FL", pct: 0.0, streak: 0, weeks: "eeheetteeeetheheeebbetheeeheeetbteeeeeeeh", week_count: 41, offset: 1 },
]

// ─── Palette (Meridian parchment family) ──────────────────────

const INK = "#1a1408"     // matches --dark
const SEPIA = "#5c4a38"   // slightly darker to read on the dirtier stock
const PARCHMENT = "#f0e8d0" // matches --light (WFRP aged paper)
const RULE = "#c4b898"    // visible on the darker stock

const WEEK_COLOR: Record<string, string> = {
  u: INK, // unbroken
  e: "#c49a3a", // early release (amber)
  t: SEPIA, // teacher / PD / weather makeup
  h: "#8b1a1a", // holiday — dark red (WFRP Chaos accent)
  // 'b' (break) drawn as hollow cell — see render
}

// ─── Typography helpers ──────────────────────────────────────
// Canvas 2D can't consume OpenType feature strings the way CSS
// can, so Hoefler's typographic wishlist gets translated into
// what Canvas 2D actually exposes:
//
//   · tabular lining figures → right-aligned value columns so the
//     % signs (and decimal points) land on the same x-coordinate
//   · true small caps → uppercase at ~85% size with letter tracking
//     via ctx.letterSpacing (Chrome 99+, fallback: manual spacing)
//   · balanced ragged-right → binary-search the max-width downward
//     until the line count would tick up, then use the tightest
//     width that keeps the same line count (Knuth-Plass, poor man's)

function drawSmallCaps(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  font: string,
  tracking: string,
) {
  const prevFont = ctx.font
  const prevSpacing = (ctx as CanvasRenderingContext2D & { letterSpacing?: string })
    .letterSpacing
  ctx.font = font
  try {
    ;(ctx as CanvasRenderingContext2D & { letterSpacing?: string }).letterSpacing = tracking
  } catch {
    // older browsers: ignore tracking, still draw
  }
  ctx.fillText(text.toUpperCase(), x, y)
  try {
    ;(ctx as CanvasRenderingContext2D & { letterSpacing?: string }).letterSpacing =
      prevSpacing ?? "0px"
  } catch {
    // ignore
  }
  ctx.font = prevFont
}

function measureSmallCaps(
  ctx: CanvasRenderingContext2D,
  text: string,
  font: string,
  tracking: string,
): number {
  const prevFont = ctx.font
  const prevSpacing = (ctx as CanvasRenderingContext2D & { letterSpacing?: string })
    .letterSpacing
  ctx.font = font
  try {
    ;(ctx as CanvasRenderingContext2D & { letterSpacing?: string }).letterSpacing = tracking
  } catch {
    // ignore
  }
  const w = ctx.measureText(text.toUpperCase()).width
  try {
    ;(ctx as CanvasRenderingContext2D & { letterSpacing?: string }).letterSpacing =
      prevSpacing ?? "0px"
  } catch {
    // ignore
  }
  ctx.font = prevFont
  return w
}

// Balanced ragged-right: find the tightest max-width that still
// produces the same number of lines as the caller's starting width.
// Cheap version of Knuth-Plass — avoids one very long and one very
// short line at the end of a block.
function balanceWidth(
  ctx: CanvasRenderingContext2D,
  text: string,
  font: string,
  maxWidth: number,
  lineHeight: number,
): number {
  const baseline = layoutText(ctx, text, font, maxWidth, lineHeight).lines.length
  let lo = Math.floor(maxWidth * 0.72)
  let hi = maxWidth
  while (lo < hi) {
    const mid = Math.floor((lo + hi) / 2)
    const n = layoutText(ctx, text, font, mid, lineHeight).lines.length
    if (n === baseline) hi = mid
    else lo = mid + 1
  }
  return lo
}

// ─── Typography helper (Pretext + naive fallback) ─────────────

function layoutText(
  ctx: CanvasRenderingContext2D,
  text: string,
  font: string,
  maxWidth: number,
  lineHeight: number,
): { lines: string[]; width: number } {
  ctx.font = font
  const lines: string[] = []
  let width = 0
  try {
    const prepared = prepareWithSegments(text, font)
    const result = layoutWithLines(prepared, maxWidth, lineHeight)
    for (const line of result.lines) {
      lines.push(line.text)
      width = Math.max(width, line.width)
    }
  } catch {
    const m = ctx.measureText(text)
    if (m.width > maxWidth) {
      const words = text.split(" ")
      let current = ""
      for (const w of words) {
        const test = current ? `${current} ${w}` : w
        if (ctx.measureText(test).width > maxWidth && current) {
          lines.push(current)
          current = w
        } else {
          current = test
        }
      }
      if (current) lines.push(current)
    } else {
      lines.push(text)
    }
    width = Math.min(m.width, maxWidth)
  }
  if (lines.length === 0) lines.push(text)
  if (width === 0) width = Math.min(ctx.measureText(text).width, maxWidth)
  return { lines, width }
}

// ─── Derived per-district stats ───────────────────────────────
// disruptedWeeks = weeks that contain ANY non-instructional day.
// That's the number of weeks a parent's PTO would need to cover
// if they wanted a continuous at-home presence on every disruption.

function disruptedWeeks(d: District): number {
  let n = 0
  for (const c of d.weeks) if (c !== "u") n++
  return n
}

// ─── Interactive sentence (Victor Bret's slider) ──────────────
// A live sentence above the chart that rewrites on every tick.
// The sentence's *shape* changes based on whether PTO covers the
// disrupted weeks, partially covers, or overflows — not just the
// numbers. Pretext re-lays the whole paragraph per-frame so line
// breaks stay honest as word counts change.

function buildSentence(districtIndex: number, pto: number): string {
  const d = DISTRICTS[districtIndex]
  const disrupted = disruptedWeeks(d)
  const whose = "Your kid's district"

  if (d.pct === 0) {
    // Miami-Dade edge case — every week is technically disrupted
    return `${whose}, ${d.name}, releases elementary students early every Wednesday of the year. Under a strict definition, no week is unbroken — a ${pto}-day PTO bank doesn't fit this failure mode, because the disruption is every week, not some weeks.`
  }
  if (pto === 0) {
    return `${whose} is ${d.name}. It has ${disrupted} weeks with at least one disruption. You have no paid days off. Every one of those weeks is a scramble.`
  }
  if (pto >= disrupted) {
    const leftover = pto - disrupted
    if (leftover === 0) {
      return `${whose} is ${d.name}. It has ${disrupted} weeks with at least one disruption. Your ${pto} days of PTO cover every single one — with zero days to spare for anything else in your life.`
    }
    return `${whose} is ${d.name}. It has ${disrupted} weeks with at least one disruption. Your ${pto} days of PTO cover every single one, with ${leftover} ${leftover === 1 ? "day" : "days"} left over for a funeral, a flu, or an actual vacation.`
  }
  const uncovered = disrupted - pto
  return `${whose} is ${d.name}. It has ${disrupted} weeks with at least one disruption. Your ${pto} days of PTO cover ${pto} of them. The other ${uncovered} ${uncovered === 1 ? "week is" : "weeks are"} unsolved — a grandparent, a sitter, a sick day spent at the kitchen table, or a kid home alone.`
}

function renderSentence(
  canvas: HTMLCanvasElement,
  text: string,
  maxWidth: number,
) {
  const ctx = canvas.getContext("2d")
  if (!ctx) return
  const dpr = Math.min(window.devicePixelRatio || 1, 2)
  const font = "italic 15px 'IM Fell English', 'Georgia', serif"
  const lineHeight = 22
  const padX = 20
  const padY = 14

  // Probe a temporary layout to learn the height
  ctx.font = font
  const layout = layoutText(ctx, text, font, maxWidth - padX * 2, lineHeight)
  const height = padY * 2 + layout.lines.length * lineHeight

  canvas.width = Math.ceil(maxWidth * dpr)
  canvas.height = Math.ceil(height * dpr)
  canvas.style.width = "100%"
  canvas.style.maxWidth = `${maxWidth}px`
  canvas.style.height = `${height}px`
  canvas.style.display = "block"

  ctx.setTransform(1, 0, 0, 1, 0, 0)
  ctx.scale(dpr, dpr)
  ctx.fillStyle = PARCHMENT
  ctx.fillRect(0, 0, maxWidth, height)

  // Left accent rule (Bret-ish: the sentence is a living object)
  ctx.fillStyle = "#8b1a1a" // WFRP red
  ctx.fillRect(0, padY, 3, height - padY * 2)

  ctx.font = font
  ctx.fillStyle = INK
  ctx.textAlign = "left"
  ctx.textBaseline = "top"
  let y = padY
  for (const line of layout.lines) {
    ctx.fillText(line, padX, y)
    y += lineHeight
  }
}

// ─── Render ───────────────────────────────────────────────────

function render(container: HTMLElement) {
  if (container.dataset.rendered === "true") return
  container.dataset.rendered = "true"

  // Geometry
  const chartPad = 20
  const labelAreaWidth = 200
  const valueAreaWidth = 56
  const cellW = 10
  const cellH = 14
  const cellGap = 1
  const stripWidth = TOTAL_COLUMNS * (cellW + cellGap) - cellGap
  const rowHeight = cellH + 5

  const titleSpace = 60
  const monthHeaderSpace = 22
  const legendSpace = 44
  const captionSpace = 56

  const width = labelAreaWidth + stripWidth + valueAreaWidth + chartPad * 2
  const height =
    titleSpace +
    monthHeaderSpace +
    DISTRICTS.length * rowHeight +
    legendSpace +
    captionSpace +
    chartPad * 2

  // Canvas setup with DPR scaling
  const canvas = document.createElement("canvas")
  const dpr = Math.min(window.devicePixelRatio || 1, 2)
  canvas.width = Math.ceil(width * dpr)
  canvas.height = Math.ceil(height * dpr)
  canvas.style.width = "100%"
  canvas.style.maxWidth = `${width}px`
  canvas.style.height = "auto"
  canvas.style.display = "block"
  canvas.style.margin = "2rem auto"
  canvas.setAttribute("role", "img")
  canvas.setAttribute(
    "aria-label",
    "Calendar-aligned weekly disruption strips for 23 US school districts, 2025-26 school year. Each row is one district; each cell is one week colored by whether it was an unbroken five-day week or the type of disruption. Columns align to calendar weeks, so winter break, Thanksgiving, and spring break appear in the same column across districts. Cobb County at 73% unbroken has the cleanest rhythm; Miami-Dade at 0% is visible as a row of amber cells because every Wednesday is an early-release day for grades 2-5.",
  )
  const ctx = canvas.getContext("2d")
  if (!ctx) return
  ctx.scale(dpr, dpr)

  // Parchment background
  ctx.fillStyle = PARCHMENT
  ctx.fillRect(0, 0, width, height)

  // ── Title ────────────────────────────────────────────────
  const titleFont = "italic 17px 'IM Fell English', 'Georgia', serif"
  const titleLineHeight = 22
  const titleLayout = layoutText(
    ctx,
    "The shape of the 2025–26 school year, 23 districts",
    titleFont,
    width - chartPad * 2,
    titleLineHeight,
  )
  ctx.font = titleFont
  ctx.fillStyle = INK
  ctx.textAlign = "left"
  ctx.textBaseline = "top"
  let titleY = chartPad
  for (const line of titleLayout.lines) {
    ctx.fillText(line, chartPad, titleY)
    titleY += titleLineHeight
  }

  // Subtitle — true small caps (uppercase + tracking at ~85% size)
  const subtitleFont = "10px 'IM Fell English', 'Georgia', serif"
  ctx.fillStyle = SEPIA
  ctx.textAlign = "left"
  ctx.textBaseline = "top"
  drawSmallCaps(
    ctx,
    "Each row is one district · each cell is one week · columns are calendar-aligned",
    chartPad,
    chartPad + titleLineHeight + 4,
    subtitleFont,
    "1.2px",
  )

  // ── Month header (small caps) ─────────────────────────────
  const stripX0 = chartPad + labelAreaWidth
  const headerY = titleSpace + chartPad
  const monthFont = "9px 'IM Fell English', 'Georgia', serif"
  ctx.fillStyle = SEPIA
  ctx.textAlign = "left"
  ctx.textBaseline = "top"
  for (const m of MONTH_STARTS) {
    const x = stripX0 + m.col * (cellW + cellGap)
    drawSmallCaps(ctx, m.label, x, headerY, monthFont, "0.8px")
  }
  // Hairline separator under month labels
  ctx.strokeStyle = RULE
  ctx.lineWidth = 1
  ctx.beginPath()
  ctx.moveTo(stripX0 - 4, headerY + 16)
  ctx.lineTo(stripX0 + stripWidth + 4, headerY + 16)
  ctx.stroke()

  // ── Rows ─────────────────────────────────────────────────
  const rowTop = titleSpace + chartPad + monthHeaderSpace
  const labelFont = "13px 'IM Fell English', 'Georgia', serif"
  const valueFont = "bold 13px 'IM Fell English', 'Georgia', serif"

  for (let i = 0; i < DISTRICTS.length; i++) {
    const d = DISTRICTS[i]
    const y = rowTop + i * rowHeight

    // District label (right-aligned into label area)
    const label = `${d.name} (${d.state})`
    const labelLayout = layoutText(ctx, label, labelFont, labelAreaWidth - 10, 14)
    ctx.font = labelFont
    ctx.fillStyle = INK
    ctx.textAlign = "right"
    ctx.textBaseline = "middle"
    ctx.fillText(labelLayout.lines[0], chartPad + labelAreaWidth - 10, y + cellH / 2)

    // Strip cells
    for (let j = 0; j < d.weeks.length; j++) {
      const code = d.weeks[j]
      const col = d.offset + j
      const x = stripX0 + col * (cellW + cellGap)
      if (code === "b") {
        // Hollow cell for break
        ctx.fillStyle = PARCHMENT
        ctx.fillRect(x, y, cellW, cellH)
        ctx.strokeStyle = RULE
        ctx.lineWidth = 1
        ctx.strokeRect(x + 0.5, y + 0.5, cellW - 1, cellH - 1)
      } else {
        ctx.fillStyle = WEEK_COLOR[code] || INK
        ctx.fillRect(x, y, cellW, cellH)
      }
    }

    // Percent value — right-aligned so decimals and % stack like
    // true tabular lining figures (Hoefler: the value column should
    // read as a column, not a ragged list).
    ctx.font = valueFont
    ctx.fillStyle = INK
    ctx.textAlign = "right"
    ctx.textBaseline = "middle"
    ctx.fillText(
      `${d.pct.toFixed(1)}%`,
      stripX0 + stripWidth + valueAreaWidth - 6,
      y + cellH / 2,
    )
  }

  // ── Legend ───────────────────────────────────────────────
  const legendY = rowTop + DISTRICTS.length * rowHeight + 14
  const legendItems: { code: string; label: string }[] = [
    { code: "u", label: "unbroken" },
    { code: "e", label: "early release" },
    { code: "t", label: "teacher / PD" },
    { code: "h", label: "holiday" },
    { code: "b", label: "break" },
  ]
  const legendFont = "10px 'IM Fell English', 'Georgia', serif"
  const legendTracking = "1px"
  ctx.textAlign = "left"
  ctx.textBaseline = "middle"
  let legendX = chartPad + labelAreaWidth
  for (const item of legendItems) {
    if (item.code === "b") {
      ctx.fillStyle = PARCHMENT
      ctx.fillRect(legendX, legendY - cellH / 2, cellW, cellH)
      ctx.strokeStyle = RULE
      ctx.strokeRect(legendX + 0.5, legendY - cellH / 2 + 0.5, cellW - 1, cellH - 1)
    } else {
      ctx.fillStyle = WEEK_COLOR[item.code]
      ctx.fillRect(legendX, legendY - cellH / 2, cellW, cellH)
    }
    ctx.fillStyle = SEPIA
    const labelWidth = measureSmallCaps(ctx, item.label, legendFont, legendTracking)
    drawSmallCaps(ctx, item.label, legendX + cellW + 5, legendY, legendFont, legendTracking)
    legendX += cellW + 5 + labelWidth + 18
  }

  // ── Caption (balanced ragged-right) ──────────────────────
  const captionFont = "italic 11px 'IM Fell English', 'Georgia', serif"
  const captionLineHeight = 14
  const caption =
    "Sorted by percent of unbroken five-day weeks. Weeks are full Mon-Fri blocks inside each district's school year; partial opening and closing weeks are excluded, matching the methodology that produced districts.csv. Unbroken counts reconcile exactly to the published dataset. Fairfax calibrated to the district's own per-quarter footer totals."
  const captionMaxWidth = width - chartPad * 2
  const captionBalanced = balanceWidth(
    ctx,
    caption,
    captionFont,
    captionMaxWidth,
    captionLineHeight,
  )
  const captionLayout = layoutText(
    ctx,
    caption,
    captionFont,
    captionBalanced,
    captionLineHeight,
  )
  ctx.font = captionFont
  ctx.fillStyle = SEPIA
  ctx.textAlign = "left"
  ctx.textBaseline = "top"
  let captionY = legendY + 18
  for (const line of captionLayout.lines) {
    ctx.fillText(line, chartPad, captionY)
    captionY += captionLineHeight
  }

  // ── Interactive panel (slider + dropdown + live sentence) ────
  const panel = document.createElement("div")
  panel.style.maxWidth = `${width}px`
  panel.style.margin = "1.5rem auto 0.5rem"
  panel.style.fontFamily = "'IM Fell English', 'Georgia', serif"
  panel.style.color = INK

  const controls = document.createElement("div")
  controls.style.display = "flex"
  controls.style.flexWrap = "wrap"
  controls.style.gap = "1.25rem"
  controls.style.alignItems = "center"
  controls.style.padding = "0.5rem 1rem"
  controls.style.borderTop = `1px solid ${RULE}`
  controls.style.borderBottom = `1px solid ${RULE}`
  controls.style.fontSize = "13px"

  // PTO slider
  const ptoWrap = document.createElement("label")
  ptoWrap.style.display = "flex"
  ptoWrap.style.alignItems = "center"
  ptoWrap.style.gap = "0.5rem"
  const ptoLabel = document.createElement("span")
  ptoLabel.textContent = "Your paid days off:"
  ptoLabel.style.fontStyle = "italic"
  ptoLabel.style.color = SEPIA
  const ptoInput = document.createElement("input")
  ptoInput.type = "range"
  ptoInput.min = "0"
  ptoInput.max = "30"
  ptoInput.value = "14"
  ptoInput.style.width = "160px"
  ptoInput.style.accentColor = "#8b1a1a"
  const ptoValue = document.createElement("strong")
  ptoValue.textContent = "14"
  ptoValue.style.minWidth = "1.5ch"
  ptoValue.style.fontVariantNumeric = "tabular-nums"
  ptoWrap.appendChild(ptoLabel)
  ptoWrap.appendChild(ptoInput)
  ptoWrap.appendChild(ptoValue)

  // District select
  const distWrap = document.createElement("label")
  distWrap.style.display = "flex"
  distWrap.style.alignItems = "center"
  distWrap.style.gap = "0.5rem"
  const distLabel = document.createElement("span")
  distLabel.textContent = "Your district:"
  distLabel.style.fontStyle = "italic"
  distLabel.style.color = SEPIA
  const distSelect = document.createElement("select")
  distSelect.style.fontFamily = "inherit"
  distSelect.style.fontSize = "13px"
  distSelect.style.padding = "2px 6px"
  distSelect.style.background = PARCHMENT
  distSelect.style.color = INK
  distSelect.style.border = `1px solid ${RULE}`
  const defaultIdx = DISTRICTS.findIndex((d) => d.name === "Philadelphia")
  for (let i = 0; i < DISTRICTS.length; i++) {
    const opt = document.createElement("option")
    opt.value = String(i)
    opt.textContent = `${DISTRICTS[i].name} (${DISTRICTS[i].state})`
    if (i === defaultIdx) opt.selected = true
    distSelect.appendChild(opt)
  }
  distWrap.appendChild(distLabel)
  distWrap.appendChild(distSelect)

  controls.appendChild(ptoWrap)
  controls.appendChild(distWrap)

  // Sentence canvas
  const sentenceCanvas = document.createElement("canvas")
  sentenceCanvas.style.margin = "0 auto"

  const update = () => {
    const pto = parseInt(ptoInput.value, 10)
    const idx = parseInt(distSelect.value, 10)
    ptoValue.textContent = String(pto)
    const text = buildSentence(idx, pto)
    renderSentence(sentenceCanvas, text, width)
  }
  ptoInput.addEventListener("input", update)
  distSelect.addEventListener("change", update)

  panel.appendChild(controls)
  panel.appendChild(sentenceCanvas)

  container.replaceChildren(panel, canvas)
  update()
}

// ─── Bootstrap (SPA-safe) ─────────────────────────────────────

function renderAll() {
  const containers = document.querySelectorAll<HTMLElement>(".school-calendar-chart")
  containers.forEach((c) => {
    delete c.dataset.rendered
    render(c)
  })
}

document.addEventListener("nav", renderAll)
